org: nasanbat
app: demo
service: demoday
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region`: ap-southeast-1

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript
  - serverless-offline
